name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs + Theme
        run: |
          pip install mkdocs-material

      - name: Build MkDocs site
        # Wir wechseln ins documentation-/Verzeichnis
        working-directory: documentation
        run: mkdocs build --site-dir public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          # Der public-Ordner liegt in documentation/public
          publish_dir: documentation/public
